/* changeBackground - Changes background color based on the page title (simple
   colors or hex colors) */
const changeBackground = () => {
    /* Change background color */
    if (document.title == simple_page_title) {
        const color = getRandomSimpleColor();
        changeStyles(getRandomSimpleColor());
    } else if (document.title == hex_page_title) {
        const color = getRandomHexColor();
        changeStyles(getRandomHexColor());
    }

    /* Change button color depending on background brigthness*/
    if (isBackgroundTooDarkOrBright() == "bright") {
        makeBtnDark();
    } else if (isBackgroundTooDarkOrBright() == "dark") {
        makeBtnBright();
    } else {
        makeBtnDark();
    }
};

/* getRandomSimpleColor - Returns a random simple color from json data */
const getRandomSimpleColor = () => {
    const random_index = getRandomIndex(json_data["named_colors"].length);
    const color = json_data["named_colors"][random_index];
    return color;
};

/* getRandomHexColor - Returns a random hex color from json data */
const getRandomHexColor = () => {
    let color = "#";
    for (let i = 0; i < 6; i++) {
        const random_index = getRandomIndex(json_data["hex"].length);
        color += json_data["hex"][random_index];
    }
    return color;
};

/* makeBtnBright - Makes the click me button bright */
const makeBtnBright = () => {
    btn.classList.remove("dark-btn");
    btn.classList.add("bright-btn");
};

/* makeBtnDark - Makes the click me button dark */
const makeBtnDark = () => {
    btn.classList.remove("bright-btn");
    btn.classList.add("dark-btn");
};

/* changeStyles - Change each element style for the respective color */
const changeStyles = (color) => {
    main.style.backgroundColor = color;
    color_text.textContent = color;
    color_text.style.color = color;
};

/* getRandomIndex - Return a random index using the array length */
const getRandomIndex = (json_data_length) => {
    return Math.floor(Math.random() * json_data_length);
};

/* fetchData - Fetches the data.json content to be used to change background colors */
const fetchData = async () => {
    let fetched_data = "";
    await fetch("../data/data.json")
        .then((resp) => resp.json())
        .then((data) => (fetched_data = data))
        .catch((err) => console.log(err));
    return fetched_data;
};

/* isBackgroundTooDarkOrBright - Checks if the background is bright, dark or normal */
/* FUNCTION GENERATED BY CHATGPT! */
function isBackgroundTooDarkOrBright() {
    // Get the RGB values from the main element as string
    const computedStyle = getComputedStyle(main);
    const backgroundColor = computedStyle.backgroundColor;

    // Convert the background color to RGB components
    const rgb = backgroundColor.match(/\d+/g);
    const r = parseInt(rgb[0]);
    const g = parseInt(rgb[1]);
    const b = parseInt(rgb[2]);

    // Calculate the perceived brightness using the formula
    const brightness = (r * 299 + g * 587 + b * 114) / 1000;

    // Define a threshold for darkness and brightness
    const darkThreshold = 125; // Adjust as needed
    const brightThreshold = 200; // Adjust as needed

    // Check if the brightness is too dark or too bright
    if (brightness < darkThreshold) {
        return "dark";
    } else if (brightness > brightThreshold) {
        return "bright";
    } else {
        return "normal";
    }
}

/* copyColorToClipboard - Copy the text from the color to the clipboard */
const copyColorToClipboard = async () => {
    try {
        await navigator.clipboard.writeText(color_text.textContent);
        clipboard_message.classList.add("show");
        const color_text_content = color_text.textContent.toLocaleUpperCase();
        clipboard_message.textContent = `Copied ${color_text_content} to clipboard ✅`;
        setTimeout(() => {
            clipboard_message.classList.remove("show");
        }, 3000);
    } catch (err) {
        console.error(`Error: ${err}`);
    }
};

/* General Variables */
const btn = document.querySelector(".btn");
const color_text = document.querySelector(".color");
const main = document.querySelector("main");
const clipboard_message = document.querySelector(".message");
const simple_page_title = "Color Flipper - Simple Colors";
const hex_page_title = "Color Flipper - Hex Colors";
let json_data = [];

/* Events */
btn.addEventListener("click", () => {
    changeBackground();
});

document.addEventListener("DOMContentLoaded", async () => {
    try {
        json_data = await fetchData();
        changeBackground();
    } catch (err) {
        console.error(`Error: ${err}`);
    }
});

color_text.addEventListener("click", async function () {
    copyColorToClipboard();
});
